# Generated by Django 5.0.6 on 2024-07-05 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JyT', '0003_producto_carrito_carritoitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carritoitem',
            name='carrito',
        ),
        migrations.RemoveField(
            model_name='carritoitem',
            name='producto',
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(default='no_imagen.jpg', upload_to='productos'),
        ),
        migrations.DeleteModel(
            name='Carrito',
        ),
        migrations.DeleteModel(
            name='CarritoItem',
        ),
    ]
